apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: wv67loxsz-dotnet-basic-gitops
  description: This is GitOps manifest for wv67loxsz-dotnet-basic   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: wv67loxsz-dotnet-basic
    janus-idp.io/tekton: wv67loxsz-dotnet-basic 
    backstage.io/kubernetes-id: wv67loxsz-dotnet-basic 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:wv67loxsz-dotnet-basic
